### ISSUE TITLE
geojson support

### ISSUE THREAD

**Issue by zhongshuiyuan** [AegisSpatial/aegis-origin#1]
Whether geojson is supported?

**Comment by mcserep** [comment]
Hello!

I have just pushed a previously unmerged feature for GeoJson and TopoJson support, check out the `geojson` branch to use / test it until it gets merged.
Details: #2

**Comment by zhongshuiyuan** [comment]
> Hello!
> 
> I have just pushed a previously unmerged feature for GeoJson and TopoJson support, check out the `geojson` branch to use / test it until it gets merged.
> Details: #2

Thank you very much. This is very useful. If can extract the transformation between GeometryObject and IGeometry from GeoJsonReader, it will be better. Thanks again!
